openapi: 3.0.3
info:
  title: Personal Expense Tracker
  version: 1.0.0
  description: Track your Income, Expenses and set Budgets
paths:
  /api/auth/login/:
    post:
      operationId: auth_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/auth/user/:
    get:
      operationId: auth_user_retrieve
      tags:
      - auth
      responses:
        '200':
          description: No response body
  /api/budgets/add/:
    post:
      operationId: budgets_add_create
      tags:
      - budgets
      responses:
        '200':
          description: No response body
  /api/budgets/stats/{month}/:
    get:
      operationId: budgets_stats_retrieve
      parameters:
      - in: path
        name: month
        schema:
          type: integer
        required: true
      tags:
      - budgets
      responses:
        '200':
          description: No response body
  /api/categories/add/:
    post:
      operationId: categories_add_create
      tags:
      - categories
      responses:
        '200':
          description: No response body
  /api/categories/all/:
    get:
      operationId: categories_all_retrieve
      tags:
      - categories
      responses:
        '200':
          description: No response body
  /api/protected/:
    get:
      operationId: protected_retrieve
      tags:
      - protected
      responses:
        '200':
          description: No response body
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/transactions/add/:
    post:
      operationId: transactions_add_create
      tags:
      - transactions
      responses:
        '200':
          description: No response body
  /api/transactions/all/:
    get:
      operationId: transactions_all_retrieve
      tags:
      - transactions
      responses:
        '200':
          description: No response body
  /api/transactions/delete/{transaction_id}/:
    delete:
      operationId: transactions_delete_destroy
      parameters:
      - in: path
        name: transaction_id
        schema:
          type: integer
        required: true
      tags:
      - transactions
      responses:
        '204':
          description: No response body
  /api/transactions/summary/:
    get:
      operationId: transactions_summary_retrieve
      tags:
      - transactions
      responses:
        '200':
          description: No response body
  /api/transactions/update/{transaction_id}/:
    put:
      operationId: transactions_update_update
      parameters:
      - in: path
        name: transaction_id
        schema:
          type: integer
        required: true
      tags:
      - transactions
      responses:
        '200':
          description: No response body
components:
  schemas:
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
